@startuml
left to right direction
actor Admin
package Situation {
  Admin --> (Create Situation)
  Admin --> (Print Situation)
}

package Itinerary {
  Admin --> (Create Itinerary)
  Admin --> (Print Itinerary)
  Admin --> (Step deep in Itinerary)
}
@enduml