@startuml
package Piece{
    class CSSColorCode {
        hex_code: string
    }
    class Color {
        color_id: integer
        name: string
    }
    class Piece {
        number: integer
    }

    Color "main_color" *--> CSSColorCode
    Color "secondary_color" *--> CSSColorCode
    Piece "up" *--> Color
    Piece "down" *--> Color
    Piece "left" *--> Color
    Piece "right" *--> Color
    class RotatedPiece
    class Rotation
    RotatedPiece o--> Rotation
    RotatedPiece o--> Piece
    Rotation <|-- Degree0
    Rotation <|-- Degree90
    Rotation <|-- Degree180
    Rotation <|-- Degree270
}
package Game{
    class Board
    class Square
    class PieceSet

    Board *--> "1.N" Square
    PieceSet *--> "N" Piece.Color: Possible
    PieceSet *--> "1.N" Piece.Piece
}
package Situation {
    class Situation
    class PlacedPiece

    PlacedPiece o--> RotatedPiece
    Situation *--> "0.N" PlacedPiece
}
package Itinerary {
    class Itinerary {
        name: string
    }
    class Path
    class Step {
        order: integer
    }

    Path *--> "1.N" Step
    Itinerary *--> Path
    Step *--> "0.N" Path : "generated ones"
}
Path *--> Situation.Situation
PlacedPiece o--> Square
Step o--> Square
@enduml