@startuml
package Game{
    class Game
    class Board
    class Square
    class PieceSet
    class Piece
    class Color

    Game *--> Board
    Game *--> PieceSet
    Board *--> "1..N" Square
    PieceSet *--> "N" Color: Possible
    Piece "up" *--> Color
    Piece "down" *--> Color
    Piece "left" *--> Color
    Piece "right" *--> Color
    PieceSet *--> "1..N" Piece
}
package Situation {
    class Situation
    class PlacedPiece
    class Rotation

    PlacedPiece o--> Rotation
    Situation *--> "0..N" PlacedPiece
    Rotation <|-- Degree0
    Rotation <|-- Degree90
    Rotation <|-- Degree180
    Rotation <|-- Degree270
}
package Itinerary {
    class Itinerary {
        name: string
    }
    class Path
    class Step {
        order: integer
    }

    Path *--> "1..N" Step
    Itinerary *--> Path
    Step *--> "0..N" Path : "generated ones"
}
Path o--> Game.Game
Path *--> Situation.Situation
PlacedPiece o--> Square
PlacedPiece o--> Piece
Step o--> Square
@enduml