@startuml
package Initial{

    object itinerary {
        +name: InitialItinerary
    }

    object path_level_1

    itinerary *--> path_level_1

    object initial_situation

    path_level_1 *--> initial_situation

    object step_1_level_1
    object step_2_level_1
    object step_3_level_1
    object step_4_level_1

    path_level_1 *--> step_1_level_1
    path_level_1 *--> step_2_level_1
    path_level_1 *--> step_3_level_1
    path_level_1 *--> step_4_level_1
}
package FirstPossibilities {
    object path_2_level_2
    object path_1_level_2
    step_1_level_1 *--> path_2_level_2
    step_1_level_1 *--> path_1_level_2

    object initial_situation_plus_one_piece
    path_1_level_2 *--> initial_situation_plus_one_piece
    object step_1_level_2
    object step_2_level_2
    object step_3_level_2

    path_1_level_2 *--> step_1_level_2
    path_1_level_2 *--> step_2_level_2
    path_1_level_2 *--> step_3_level_2
}
@enduml